# Story 03.1 - Database Schema
# Purpose: Tables, RLS policies, indexes
# Agent: BACKEND-DEV (database focus)

migrations:
  - path: "supabase/migrations/XXX_create_suppliers_table.sql"
    type: "migration"
    description: "Suppliers table with RLS policies"

tables:
  - name: "suppliers"
    description: "Supplier master data for procurement"
    columns:
      - { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()" }
      - { name: "org_id", type: "UUID", constraints: "NOT NULL REFERENCES organizations(id)" }
      - { name: "code", type: "TEXT", constraints: "NOT NULL" }
      - { name: "name", type: "TEXT", constraints: "NOT NULL" }
      - { name: "address", type: "TEXT", constraints: "" }
      - { name: "city", type: "TEXT", constraints: "" }
      - { name: "postal_code", type: "TEXT", constraints: "" }
      - { name: "country", type: "TEXT", constraints: "" }  # ISO 3166-1 alpha-2
      - { name: "contact_name", type: "TEXT", constraints: "" }
      - { name: "contact_email", type: "TEXT", constraints: "" }
      - { name: "contact_phone", type: "TEXT", constraints: "" }
      - { name: "currency", type: "TEXT", constraints: "DEFAULT 'PLN' CHECK (currency IN ('PLN', 'EUR', 'USD', 'GBP'))" }
      - { name: "tax_code_id", type: "UUID", constraints: "REFERENCES tax_codes(id)" }
      - { name: "payment_terms", type: "TEXT", constraints: "NOT NULL" }
      - { name: "notes", type: "TEXT", constraints: "" }
      - { name: "is_active", type: "BOOLEAN", constraints: "DEFAULT true" }
      # Phase 3 fields (nullable for now)
      - { name: "approved_supplier", type: "BOOLEAN", constraints: "DEFAULT false" }
      - { name: "supplier_rating", type: "DECIMAL(3,2)", constraints: "" }  # 1.00-5.00
      - { name: "last_audit_date", type: "DATE", constraints: "" }
      - { name: "next_audit_due", type: "DATE", constraints: "" }
      # Audit fields
      - { name: "created_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }
      - { name: "updated_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }
      - { name: "created_by", type: "UUID", constraints: "REFERENCES users(id)" }
      - { name: "updated_by", type: "UUID", constraints: "REFERENCES users(id)" }
    rls: true
    rls_pattern: "org_id = (SELECT org_id FROM users WHERE id = auth.uid())"
    indexes:
      - "idx_suppliers_org_active ON suppliers(org_id, is_active, created_at DESC)"
      - "idx_suppliers_org_code ON suppliers(org_id, code)"
      - "idx_suppliers_org_name ON suppliers(org_id, name)"
      - "idx_suppliers_tax_code ON suppliers(tax_code_id)"
    constraints:
      - "UNIQUE(org_id, code)"
    triggers:
      - name: "suppliers_updated_at"
        timing: "BEFORE UPDATE"
        event: "UPDATE"
        function: "update_updated_at_column()"

# RLS Policies (ADR-013)
rls_policies:
  pattern: "Users Table Lookup"
  pattern_sql: "(SELECT org_id FROM users WHERE id = auth.uid())"
  rationale:
    - "Single source of truth (users table)"
    - "User org reassignment takes effect immediately"
    - "No custom JWT claim configuration required"
    - "Performance overhead <1ms per query"

  policies:
    - table: "suppliers"
      name: "suppliers_org_isolation"
      operation: "ALL"
      using: "org_id = (SELECT org_id FROM users WHERE id = auth.uid())"
      description: "Users can only access suppliers in their organization"

# Migration SQL Template
migration_sql: |
  -- Migration: Create suppliers table
  -- Story: 03.1 - Suppliers CRUD

  -- Create suppliers table
  CREATE TABLE suppliers (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id              UUID NOT NULL REFERENCES organizations(id),
    code                TEXT NOT NULL,
    name                TEXT NOT NULL,
    address             TEXT,
    city                TEXT,
    postal_code         TEXT,
    country             TEXT,
    contact_name        TEXT,
    contact_email       TEXT,
    contact_phone       TEXT,
    currency            TEXT DEFAULT 'PLN' CHECK (currency IN ('PLN', 'EUR', 'USD', 'GBP')),
    tax_code_id         UUID REFERENCES tax_codes(id),
    payment_terms       TEXT NOT NULL,
    notes               TEXT,
    is_active           BOOLEAN DEFAULT true,
    -- Phase 3 fields
    approved_supplier   BOOLEAN DEFAULT false,
    supplier_rating     DECIMAL(3,2),
    last_audit_date     DATE,
    next_audit_due      DATE,
    -- Audit fields
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW(),
    created_by          UUID REFERENCES users(id),
    updated_by          UUID REFERENCES users(id),
    -- Constraints
    UNIQUE(org_id, code)
  );

  -- Indexes
  CREATE INDEX idx_suppliers_org_active ON suppliers(org_id, is_active, created_at DESC);
  CREATE INDEX idx_suppliers_org_code ON suppliers(org_id, code);
  CREATE INDEX idx_suppliers_org_name ON suppliers(org_id, name);
  CREATE INDEX idx_suppliers_tax_code ON suppliers(tax_code_id);

  -- RLS
  ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;

  CREATE POLICY suppliers_org_isolation ON suppliers
    FOR ALL
    USING (org_id = (SELECT org_id FROM users WHERE id = auth.uid()));

  -- Trigger for updated_at
  CREATE TRIGGER suppliers_updated_at
    BEFORE UPDATE ON suppliers
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

  -- Comments
  COMMENT ON TABLE suppliers IS 'Supplier master data for procurement';
  COMMENT ON COLUMN suppliers.code IS 'Unique supplier code per org (e.g., SUP-001)';
  COMMENT ON COLUMN suppliers.country IS 'ISO 3166-1 alpha-2 country code';
  COMMENT ON COLUMN suppliers.currency IS 'Default currency for purchase orders';
  COMMENT ON COLUMN suppliers.payment_terms IS 'Payment terms (e.g., Net 30, 2/10 Net 30)';

# Notes about related tables (implemented in later stories)
future_tables:
  - name: "supplier_products"
    story: "03.2"
    description: "Links suppliers to products with pricing/lead time overrides"
  - name: "purchase_orders"
    story: "03.3"
    description: "References suppliers.id as foreign key"

# Data validation notes
validation_notes:
  - "code: 2-20 chars, alphanumeric + hyphen, uppercase"
  - "name: 2-100 chars"
  - "contact_email: valid email format if provided"
  - "contact_phone: max 50 chars"
  - "address: max 200 chars"
  - "city: max 100 chars"
  - "postal_code: max 20 chars"
  - "country: exactly 2 chars (ISO alpha-2)"
  - "payment_terms: 1-100 chars, REQUIRED"
  - "notes: max 1000 chars"
