import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

interface Product {
  id: number;
  name: string;
  line_id: number;
  allergens: string[];
}

interface ProductionLine {
  id: number;
  name: string;
}

interface AllergenData {
  id: string;
  name: string;
  severity: number;
}

interface RiskCell {
  lineId: number;
  allergen: string;
  productCount: number;
  riskScore: number;
  riskLevel: 'safe' | 'low' | 'medium' | 'high';
  products: Product[];
}

interface ExportData {
  productionLines: ProductionLine[];
  products: Product[];
  allergens: AllergenData[];
  riskMatrix: RiskCell[][];
  warnings: string[];
  generatedBy?: string;
  orgName?: string;
}

/**
 * Export Allergen Matrix to PDF
 * Generates a comprehensive PDF report with:
 * - Cover page with metadata
 * - Matrix heatmap visualization
 * - Cross-contamination warnings
 * - Detailed product lists per allergen
 */
export async function exportAllergenMatrixToPDF(data: ExportData): Promise<void> {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - 2 * margin;

  let yPos = margin;

  // ============================================================================
  // COVER PAGE
  // ============================================================================

  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Allergen Cross-Contamination Matrix', pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  // Subtitle
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text('Risk Assessment Report', pageWidth / 2, yPos, { align: 'center' });
  yPos += 20;

  // Metadata
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Report Details:', margin, yPos);
  yPos += 7;

  doc.setFont('helvetica', 'normal');
  const generatedDate = new Date().toLocaleString();
  doc.text(`Generated: ${generatedDate}`, margin, yPos);
  yPos += 6;

  if (data.generatedBy) {
    doc.text(`Generated by: ${data.generatedBy}`, margin, yPos);
    yPos += 6;
  }

  if (data.orgName) {
    doc.text(`Organization: ${data.orgName}`, margin, yPos);
    yPos += 6;
  }

  doc.text(`Production Lines: ${data.productionLines.length}`, margin, yPos);
  yPos += 6;
  doc.text(`Total Products Analyzed: ${data.products.length}`, margin, yPos);
  yPos += 6;
  doc.text(`Allergens: 14 EU Allergens (Regulation 1169/2011)`, margin, yPos);
  yPos += 15;

  // Summary Statistics
  const highRiskCount = data.riskMatrix.flat().filter((c) => c.riskLevel === 'high').length;
  const mediumRiskCount = data.riskMatrix.flat().filter((c) => c.riskLevel === 'medium').length;
  const warningCount = data.warnings.length;

  doc.setFont('helvetica', 'bold');
  doc.text('Risk Summary:', margin, yPos);
  yPos += 7;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(220, 38, 38); // Red
  doc.text(`High Risk Cells: ${highRiskCount}`, margin, yPos);
  yPos += 6;

  doc.setTextColor(234, 179, 8); // Yellow
  doc.text(`Medium Risk Cells: ${mediumRiskCount}`, margin, yPos);
  yPos += 6;

  doc.setTextColor(220, 38, 38); // Red
  doc.text(`Cross-Contamination Warnings: ${warningCount}`, margin, yPos);
  yPos += 15;

  doc.setTextColor(0, 0, 0); // Reset to black

  // ============================================================================
  // PAGE 2: RISK MATRIX HEATMAP
  // ============================================================================

  doc.addPage('landscape');
  yPos = margin;

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Allergen Risk Matrix Heatmap', margin, yPos);
  yPos += 10;

  // Draw matrix table
  const cellWidth = Math.min(25, (contentWidth - 50) / data.productionLines.length);
  const cellHeight = 8;
  const labelWidth = 50;

  // Table header
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');

  // Allergen column header
  doc.text('Allergen', margin, yPos);

  // Production line headers
  data.productionLines.forEach((line, idx) => {
    const x = margin + labelWidth + idx * cellWidth;
    doc.text(line.name, x + cellWidth / 2, yPos, { align: 'center', maxWidth: cellWidth - 2 });
  });
  yPos += 6;

  // Draw line under header
  doc.setDrawColor(100, 100, 100);
  doc.line(margin, yPos, margin + labelWidth + data.productionLines.length * cellWidth, yPos);
  yPos += 2;

  // Matrix rows
  doc.setFont('helvetica', 'normal');
  data.riskMatrix.forEach((row, rowIdx) => {
    const allergen = data.allergens[rowIdx];

    // Allergen name
    doc.setFontSize(8);
    doc.text(`${allergen.name} (${allergen.severity})`, margin, yPos + 5);

    // Risk cells
    row.forEach((cell, colIdx) => {
      const x = margin + labelWidth + colIdx * cellWidth;

      // Cell background color based on risk level
      if (cell.riskLevel === 'high') {
        doc.setFillColor(252, 165, 165); // Red-200
      } else if (cell.riskLevel === 'medium') {
        doc.setFillColor(254, 240, 138); // Yellow-200
      } else if (cell.riskLevel === 'low') {
        doc.setFillColor(187, 247, 208); // Green-200
      } else {
        doc.setFillColor(240, 253, 244); // Green-50
      }

      doc.rect(x, yPos, cellWidth, cellHeight, 'F');

      // Cell border
      doc.setDrawColor(200, 200, 200);
      doc.rect(x, yPos, cellWidth, cellHeight, 'S');

      // Cell text
      doc.setFontSize(9);
      doc.setTextColor(0, 0, 0);
      doc.text(`${cell.productCount}`, x + cellWidth / 2, yPos + 4, { align: 'center' });
      doc.setFontSize(7);
      doc.text(
        cell.riskLevel === 'safe' ? 'Safe' : `R:${cell.riskScore}`,
        x + cellWidth / 2,
        yPos + 6.5,
        { align: 'center' }
      );
    });

    yPos += cellHeight;

    // Add new page if needed
    if (yPos > pageHeight - margin - 10) {
      doc.addPage('landscape');
      yPos = margin;
    }
  });

  // Legend
  yPos += 10;
  if (yPos > pageHeight - margin - 30) {
    doc.addPage('landscape');
    yPos = margin;
  }

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Risk Levels:', margin, yPos);
  yPos += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);

  // Safe
  doc.setFillColor(240, 253, 244);
  doc.rect(margin, yPos - 3, 8, 5, 'F');
  doc.setDrawColor(200, 200, 200);
  doc.rect(margin, yPos - 3, 8, 5, 'S');
  doc.text('Safe (0 products)', margin + 10, yPos);
  yPos += 6;

  // Low
  doc.setFillColor(187, 247, 208);
  doc.rect(margin, yPos - 3, 8, 5, 'F');
  doc.rect(margin, yPos - 3, 8, 5, 'S');
  doc.text('Low (Risk 1-5)', margin + 10, yPos);
  yPos += 6;

  // Medium
  doc.setFillColor(254, 240, 138);
  doc.rect(margin, yPos - 3, 8, 5, 'F');
  doc.rect(margin, yPos - 3, 8, 5, 'S');
  doc.text('Medium (Risk 6-15)', margin + 10, yPos);
  yPos += 6;

  // High
  doc.setFillColor(252, 165, 165);
  doc.rect(margin, yPos - 3, 8, 5, 'F');
  doc.rect(margin, yPos - 3, 8, 5, 'S');
  doc.text('High (Risk 16+)', margin + 10, yPos);

  // ============================================================================
  // PAGE 3: CROSS-CONTAMINATION WARNINGS
  // ============================================================================

  if (data.warnings.length > 0) {
    doc.addPage('landscape');
    yPos = margin;

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 38, 38); // Red
    doc.text(`Cross-Contamination Warnings (${data.warnings.length})`, margin, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0, 0, 0);

    data.warnings.forEach((warning, idx) => {
      if (yPos > pageHeight - margin - 15) {
        doc.addPage('landscape');
        yPos = margin;
      }

      doc.setFont('helvetica', 'bold');
      doc.text(`${idx + 1}.`, margin, yPos);
      doc.setFont('helvetica', 'normal');
      const wrappedText = doc.splitTextToSize(warning, contentWidth - 10);
      doc.text(wrappedText, margin + 5, yPos);
      yPos += wrappedText.length * 5 + 3;
    });
  }

  // ============================================================================
  // PAGE 4+: PRODUCT DETAILS PER ALLERGEN
  // ============================================================================

  doc.addPage('landscape');
  yPos = margin;

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Product Details by Allergen', margin, yPos);
  yPos += 10;

  doc.setFontSize(10);

  data.allergens.forEach((allergen) => {
    const productsWithAllergen = data.products.filter((p) => p.allergens.includes(allergen.id));

    if (productsWithAllergen.length === 0) return;

    if (yPos > pageHeight - margin - 30) {
      doc.addPage('landscape');
      yPos = margin;
    }

    doc.setFont('helvetica', 'bold');
    doc.text(
      `${allergen.name} (${productsWithAllergen.length} product${productsWithAllergen.length !== 1 ? 's' : ''})`,
      margin,
      yPos
    );
    yPos += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);

    productsWithAllergen.forEach((product) => {
      if (yPos > pageHeight - margin - 10) {
        doc.addPage('landscape');
        yPos = margin;
      }

      const line = data.productionLines.find((l) => l.id === product.line_id);
      const allergenList = product.allergens.join(', ');

      doc.text(`• ${product.name}`, margin + 5, yPos);
      yPos += 5;
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      doc.text(`  Line: ${line?.name || 'Unknown'} | All allergens: ${allergenList}`, margin + 7, yPos);
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(9);
      yPos += 6;
    });

    yPos += 4;
  });

  // Save PDF
  const filename = `Allergen_Matrix_Report_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
