# BMad Method - Project Status

project_name: "MonoPilot (Unreal)"
project_type: "Brownfield MES System"
initialization_date: "2025-01-11"
current_phase: "document-project-completed"

# Workflow History
workflows_completed:
  - name: "workflow-init"
    completed_at: "2025-01-11"
    output:
      - "docs/bmm/sessions/2025-01-11-brainstorm-init.md"
  
  - name: "brainstorm"
    completed_at: "2025-01-11"
    decisions:
      top_challenges:
        1: "Traceability (Priority 2)"
        2: "Scanner Integration (Identified)"
        3: "BOM Complexity (Priority 1 - HIGHEST)"
        4: "Status Workflows (Identified)"
      
      roadmap:
        phase_1: "BOM Complexity Enhancement"
        phase_2: "Traceability System"
        phase_3: "Scanner Integration"
        phase_4: "Status Workflow Guards"
  
  - name: "document-project"
    completed_at: "2025-01-11"
    output:
      - "docs/bmm/artifacts/tech-spec.md"
    statistics:
      total_tables: 34
      total_api_modules: 20+
      total_components: 60+
      total_migrations: 44

# Current State Analysis
modules_status:
  settings:
    status: "complete"
    tables: ["users", "suppliers", "warehouses", "locations", "tax_codes", "allergens", "machines", "production_lines"]
  
  products_bom:
    status: "complete"
    tables: ["products", "boms", "bom_items", "bom_history"]
    features:
      - "Product catalog (5 types: RM, DG, PR, FG, WIP)"
      - "BOM lifecycle (draft → active → archived)"
      - "BOM items with rules (optional, phantom, consume_whole_lp)"
  
  planning:
    status: "in_progress"
    tables: ["po_header", "po_line", "to_header", "to_line", "work_orders", "wo_materials", "wo_operations"]
    completed_features:
      - "Transfer Orders (warehouse-to-warehouse)"
      - "Purchase Orders (with Quick Entry)"
      - "Work Orders (basic creation)"
    in_progress:
      - "TO shipping/receiving workflow"
      - "PO GRN integration"
      - "WO material reservation"
  
  production:
    status: "planned"
    tables: ["production_outputs", "license_plates", "lp_reservations"]
    planned_features:
      - "WO execution & operation tracking"
      - "LP tracking with genealogy"
      - "Scanner integration"
  
  warehouse:
    status: "planned"
    tables: ["license_plates", "stock_moves", "grns", "grn_items", "asns", "asn_items", "pallets"]
    planned_features:
      - "GRN processing"
      - "Stock moves"
      - "LP management"
  
  qa_traceability:
    status: "planned"
    tables: ["lp_genealogy", "lp_compositions"]
    planned_features:
      - "Batch tracking"
      - "LP genealogy (parent-child)"
      - "Recall reports"

# Next Steps
next_workflows:
  - name: "plan-epic"
    target: "BOM Complexity v2"
    priority: "P0"
    features:
      - "By-products support (wo_by_products table)"
      - "Multi-version BOM (effective_from/to dates)"
      - "Conditional components (condition JSONB)"
    estimated_effort: "4-6 weeks"
  
  - name: "plan-epic"
    target: "Traceability & Compliance"
    priority: "P1"
    features:
      - "LP genealogy recursive queries"
      - "Batch tracking across stages"
      - "Recall reports"
    estimated_effort: "3-4 weeks"

# Technical Debt Register
known_issues:
  - id: "TD-001"
    title: "Client State migration to API calls"
    severity: "medium"
    affected_components: ["Several modals still use clientState"]
    fix_effort: "2-3 days"
  
  - id: "TD-002"
    title: "Missing E2E tests"
    severity: "medium"
    coverage: "0% E2E (Playwright setup exists but no tests)"
    fix_effort: "1 week"
  
  - id: "TD-003"
    title: "No API documentation"
    severity: "low"
    solution: "Generate OpenAPI/Swagger spec"
    fix_effort: "2 days"

# Documentation Status
documentation:
  complete:
    - "01_system_overview.md"
    - "11_PROJECT_STRUCTURE.md"
    - "12_DATABASE_TABLES.md"
    - "13_DATABASE_MIGRATIONS.md"
    - "14_NIESPOJNOSCI_FIX_CHECKLIST.md"
    - "15_DOCUMENTATION_AUDIT.md"
    - "bmm/artifacts/tech-spec.md"
    - "bmm/sessions/2025-01-11-brainstorm-init.md"
  
  missing:
    - "API Reference (OpenAPI)"
    - "Component Library (Storybook)"
    - "Deployment Guide"
    - "User Manual"
    - "Troubleshooting Guide"

# Metrics
codebase_metrics:
  lines_of_code: "~50,000 (estimated)"
  test_coverage: "~60% unit tests"
  database_tables: 34
  migrations: 44
  api_modules: 20+
  components: 60+
  routes: "~15 (Next.js App Router)"

# Team & Roles
team:
  - name: "Mariusz K"
    role: "Project Lead / Technical Architect"
    focus: ["BOM module", "Planning module", "Database architecture"]

# BMad Method Configuration
bmad_config:
  version: "6.0.0-alpha.8"
  installed: true
  modules:
    - "bmm" # BMad Method Module
    - "bmb" # BMad Base
    - "bmgd" # BMad Greenfield/Domain
    - "cis" # Code Integrity System
  
  agents_configured:
    - "bmm-architect"
    - "bmm-analyst"
    - "bmm-planner"
    - "bmm-dev"
    - "bmm-qa"

# Notes
notes: |
  This is a brownfield project with significant existing codebase.
  The project follows Filament-style UI/UX design patterns.
  All database migrations are organized (000-043), one per table.
  RLS is enabled on 33/34 tables for security.
  
  Key architectural decisions:
  - Transfer Orders are warehouse-to-warehouse (not location-to-location)
  - BOM uses snapshot pattern for WO materials
  - License Plates are the core traceability unit
  
  Focus areas for next phase:
  1. BOM Complexity (by-products, versioning, conditional components)
  2. Traceability (LP genealogy, batch tracking, recall reports)

