# Story 02.1 - Database Schema
# Purpose: Tables, RLS policies, indexes, seed data
# Agent: BACKEND-DEV (database focus)

migrations:
  - path: "supabase/migrations/XXX_create_product_types_table.sql"
    type: "migration"
    description: "Product types reference table with seed data"
  - path: "supabase/migrations/XXX_create_products_table.sql"
    type: "migration"
    description: "Products table with all fields including ADR-010 procurement fields"

tables:
  - name: "product_types"
    description: "Product type reference table - seeded, immutable codes"
    columns:
      - { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()" }
      - { name: "org_id", type: "UUID", constraints: "NOT NULL REFERENCES organizations(id)" }
      - { name: "code", type: "VARCHAR(10)", constraints: "NOT NULL" }
      - { name: "name", type: "VARCHAR(100)", constraints: "NOT NULL" }
      - { name: "is_default", type: "BOOLEAN", constraints: "DEFAULT false" }
      - { name: "is_active", type: "BOOLEAN", constraints: "DEFAULT true" }
      - { name: "created_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }
    rls: true
    rls_pattern: "org_id = (SELECT org_id FROM users WHERE id = auth.uid())"
    indexes:
      - "idx_product_types_org_code ON product_types(org_id, code)"
    constraints:
      - "UNIQUE(org_id, code)"

  - name: "products"
    description: "Main product table with all fields per PRD and ADR-010"
    columns:
      # Core fields
      - { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()" }
      - { name: "org_id", type: "UUID", constraints: "NOT NULL REFERENCES organizations(id)" }
      - { name: "code", type: "VARCHAR(50)", constraints: "NOT NULL" }
      - { name: "name", type: "VARCHAR(255)", constraints: "NOT NULL" }
      - { name: "description", type: "TEXT", constraints: "" }
      - { name: "product_type_id", type: "UUID", constraints: "NOT NULL REFERENCES product_types(id)" }
      - { name: "base_uom", type: "VARCHAR(20)", constraints: "NOT NULL" }
      - { name: "status", type: "VARCHAR(20)", constraints: "DEFAULT 'active'" }
      - { name: "version", type: "INTEGER", constraints: "DEFAULT 1" }
      # Identification
      - { name: "barcode", type: "VARCHAR(100)", constraints: "" }
      - { name: "gtin", type: "VARCHAR(14)", constraints: "" }
      - { name: "category_id", type: "UUID", constraints: "" }
      # Procurement (ADR-010)
      - { name: "lead_time_days", type: "INTEGER", constraints: "DEFAULT 7" }
      - { name: "moq", type: "DECIMAL(10,2)", constraints: "" }
      # Costing (FR-2.13, FR-2.15)
      - { name: "std_price", type: "DECIMAL(15,4)", constraints: "" }
      - { name: "cost_per_unit", type: "DECIMAL(15,4)", constraints: "" }
      # Stock Control
      - { name: "min_stock", type: "DECIMAL(15,4)", constraints: "" }
      - { name: "max_stock", type: "DECIMAL(15,4)", constraints: "" }
      # Shelf Life (FR-2.14)
      - { name: "expiry_policy", type: "VARCHAR(20)", constraints: "DEFAULT 'none'" }
      - { name: "shelf_life_days", type: "INTEGER", constraints: "" }
      - { name: "storage_conditions", type: "VARCHAR(500)", constraints: "" }
      - { name: "is_perishable", type: "BOOLEAN", constraints: "DEFAULT false" }
      # Audit
      - { name: "created_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }
      - { name: "updated_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }
      - { name: "created_by", type: "UUID", constraints: "REFERENCES users(id)" }
      - { name: "updated_by", type: "UUID", constraints: "REFERENCES users(id)" }
    rls: true
    rls_pattern: "org_id = (SELECT org_id FROM users WHERE id = auth.uid())"
    indexes:
      - "idx_products_org_code ON products(org_id, code)"
      - "idx_products_org_type ON products(org_id, product_type_id)"
      - "idx_products_org_status ON products(org_id, status)"
      - "idx_products_org_name ON products(org_id, name)"
    constraints:
      - "UNIQUE(org_id, code)"
      - "CHECK (status IN ('active', 'inactive', 'discontinued'))"
      - "CHECK (expiry_policy IN ('fixed', 'rolling', 'none'))"
      - "CHECK (lead_time_days IS NULL OR lead_time_days >= 0)"
      - "CHECK (moq IS NULL OR moq > 0)"
      - "CHECK (min_stock IS NULL OR min_stock >= 0)"
      - "CHECK (max_stock IS NULL OR max_stock >= 0)"
      - "CHECK (std_price IS NULL OR std_price >= 0)"
      - "CHECK (cost_per_unit IS NULL OR cost_per_unit >= 0)"

# RLS Policies (ADR-013)
rls_policies:
  pattern: "Users Table Lookup"
  pattern_sql: "(SELECT org_id FROM users WHERE id = auth.uid())"
  rationale:
    - "Single source of truth (users table)"
    - "User org reassignment takes effect immediately"
    - "No custom JWT claim configuration required"
    - "Performance overhead <1ms per query"

  policies:
    # product_types policies
    - table: "product_types"
      name: "product_types_org_isolation"
      operation: "SELECT"
      using: "org_id = (SELECT org_id FROM users WHERE id = auth.uid())"
    - table: "product_types"
      name: "product_types_admin_write"
      operation: "ALL"
      using: "org_id = (SELECT org_id FROM users WHERE id = auth.uid()) AND (SELECT r.code FROM roles r JOIN users u ON u.role_id = r.id WHERE u.id = auth.uid()) IN ('SUPER_ADMIN', 'ADMIN')"

    # products policies
    - table: "products"
      name: "products_org_isolation"
      operation: "SELECT"
      using: "org_id = (SELECT org_id FROM users WHERE id = auth.uid())"
    - table: "products"
      name: "products_write"
      operation: "INSERT"
      using: "org_id = (SELECT org_id FROM users WHERE id = auth.uid())"
      with_check: "org_id = (SELECT org_id FROM users WHERE id = auth.uid())"
    - table: "products"
      name: "products_update"
      operation: "UPDATE"
      using: "org_id = (SELECT org_id FROM users WHERE id = auth.uid())"
    - table: "products"
      name: "products_delete"
      operation: "DELETE"
      using: "org_id = (SELECT org_id FROM users WHERE id = auth.uid()) AND (SELECT r.code FROM roles r JOIN users u ON u.role_id = r.id WHERE u.id = auth.uid()) IN ('SUPER_ADMIN', 'ADMIN')"

# Triggers
triggers:
  - name: "trg_products_updated_at"
    table: "products"
    event: "BEFORE UPDATE"
    function: "update_updated_at_column()"
    description: "Auto-update updated_at timestamp on row update"

  - name: "trg_warn_missing_cost_per_unit"
    table: "products"
    event: "AFTER INSERT OR UPDATE"
    function: "warn_missing_cost_per_unit()"
    description: "Log warning when RM/PKG products have no cost_per_unit (FR-2.15)"
    sql: |
      CREATE OR REPLACE FUNCTION warn_missing_cost_per_unit()
      RETURNS TRIGGER AS $$
      BEGIN
        IF (SELECT code FROM product_types WHERE id = NEW.product_type_id) IN ('RM', 'PKG')
           AND NEW.cost_per_unit IS NULL THEN
          RAISE WARNING 'Product % (%) has no cost_per_unit defined',
            NEW.code,
            (SELECT code FROM product_types WHERE id = NEW.product_type_id);
        END IF;
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;

# Seed Data
seed_data:
  product_types:
    description: "5 default product types per PRD - seeded per org"
    note: "Seed data created per organization during org setup or first product creation"
    data:
      - { code: "RM", name: "Raw Material", is_default: true, color: "blue" }
      - { code: "WIP", name: "Work in Progress", is_default: true, color: "yellow" }
      - { code: "FG", name: "Finished Goods", is_default: true, color: "green" }
      - { code: "PKG", name: "Packaging", is_default: true, color: "purple" }
      - { code: "BP", name: "Byproduct", is_default: true, color: "orange" }

# Product Type Badge Colors (for frontend reference)
badge_colors:
  RM:
    name: "Raw Material"
    bg: "bg-blue-100"
    text: "text-blue-800"
    dark_bg: "dark:bg-blue-900"
    dark_text: "dark:text-blue-300"
  WIP:
    name: "Work in Progress"
    bg: "bg-yellow-100"
    text: "text-yellow-800"
    dark_bg: "dark:bg-yellow-900"
    dark_text: "dark:text-yellow-300"
  FG:
    name: "Finished Goods"
    bg: "bg-green-100"
    text: "text-green-800"
    dark_bg: "dark:bg-green-900"
    dark_text: "dark:text-green-300"
  PKG:
    name: "Packaging"
    bg: "bg-purple-100"
    text: "text-purple-800"
    dark_bg: "dark:bg-purple-900"
    dark_text: "dark:text-purple-300"
  BP:
    name: "Byproduct"
    bg: "bg-orange-100"
    text: "text-orange-800"
    dark_bg: "dark:bg-orange-900"
    dark_text: "dark:text-orange-300"

# Product Status Badge Colors
status_badge_colors:
  active:
    name: "Active"
    bg: "bg-green-100"
    text: "text-green-800"
  inactive:
    name: "Inactive"
    bg: "bg-gray-100"
    text: "text-gray-800"
  discontinued:
    name: "Discontinued"
    bg: "bg-red-100"
    text: "text-red-800"
