# Story 01.8 - Database Schema
# Purpose: Tables, RLS policies, indexes, triggers
# Agent: BACKEND-DEV (database focus)

migrations:
  - path: "supabase/migrations/065_create_warehouses_table.sql"
    type: "migration"
    description: "Create warehouses table with type enum, address, contact, and default flag"
  - path: "supabase/migrations/066_warehouses_rls_policies.sql"
    type: "migration"
    description: "RLS policies for warehouses (ADR-013 pattern) with role enforcement"

tables:
  - name: "warehouses"
    description: "Physical storage locations with type classification"
    columns:
      - { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()" }
      - { name: "org_id", type: "UUID", constraints: "NOT NULL REFERENCES organizations(id) ON DELETE CASCADE" }
      - { name: "code", type: "VARCHAR(20)", constraints: "NOT NULL" }
      - { name: "name", type: "VARCHAR(100)", constraints: "NOT NULL" }
      - { name: "type", type: "VARCHAR(20)", constraints: "NOT NULL DEFAULT 'GENERAL'" }
      - { name: "address", type: "TEXT", constraints: "" }
      - { name: "contact_email", type: "VARCHAR(255)", constraints: "" }
      - { name: "contact_phone", type: "VARCHAR(20)", constraints: "" }
      - { name: "is_default", type: "BOOLEAN", constraints: "DEFAULT false" }
      - { name: "is_active", type: "BOOLEAN", constraints: "DEFAULT true" }
      - { name: "location_count", type: "INTEGER", constraints: "DEFAULT 0" }
      - { name: "disabled_at", type: "TIMESTAMPTZ", constraints: "" }
      - { name: "disabled_by", type: "UUID", constraints: "REFERENCES users(id)" }
      - { name: "created_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }
      - { name: "updated_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }
      - { name: "created_by", type: "UUID", constraints: "REFERENCES users(id)" }
      - { name: "updated_by", type: "UUID", constraints: "REFERENCES users(id)" }

    constraints:
      - "CONSTRAINT warehouses_org_code_unique UNIQUE(org_id, code)"
      - "CONSTRAINT warehouses_type_check CHECK (type IN ('GENERAL', 'RAW_MATERIALS', 'WIP', 'FINISHED_GOODS', 'QUARANTINE'))"
      - "CONSTRAINT warehouses_code_format CHECK (code ~ '^[A-Z0-9-]{2,20}$')"
      - "CONSTRAINT warehouses_address_length CHECK (address IS NULL OR char_length(address) <= 500)"
      - "CONSTRAINT warehouses_phone_length CHECK (contact_phone IS NULL OR char_length(contact_phone) <= 20)"

    rls: true
    rls_pattern: "org_id = (SELECT org_id FROM users WHERE id = auth.uid())"

    indexes:
      - "idx_warehouses_org_id ON warehouses(org_id)"
      - "idx_warehouses_org_code ON warehouses(org_id, code)"
      - "idx_warehouses_org_type ON warehouses(org_id, type)"
      - "idx_warehouses_org_active ON warehouses(org_id, is_active)"
      - "idx_warehouses_org_default ON warehouses(org_id, is_default)"

# RLS Policies (ADR-013)
rls_policies:
  pattern: "Users Table Lookup"
  pattern_sql: "(SELECT org_id FROM users WHERE id = auth.uid())"

  policies:
    - table: "warehouses"
      name: "warehouses_select"
      operation: "SELECT"
      using: "org_id = (SELECT org_id FROM users WHERE id = auth.uid())"
      description: "All authenticated users can read org warehouses"

    - table: "warehouses"
      name: "warehouses_insert"
      operation: "INSERT"
      using: |
        org_id = (SELECT org_id FROM users WHERE id = auth.uid())
        AND (
          (SELECT r.code FROM roles r JOIN users u ON u.role_id = r.id WHERE u.id = auth.uid())
          IN ('SUPER_ADMIN', 'ADMIN', 'WAREHOUSE_MANAGER')
        )
      description: "Only admins and warehouse managers can create warehouses"

    - table: "warehouses"
      name: "warehouses_update"
      operation: "UPDATE"
      using: |
        org_id = (SELECT org_id FROM users WHERE id = auth.uid())
        AND (
          (SELECT r.code FROM roles r JOIN users u ON u.role_id = r.id WHERE u.id = auth.uid())
          IN ('SUPER_ADMIN', 'ADMIN', 'WAREHOUSE_MANAGER')
        )
      description: "Only admins and warehouse managers can update warehouses"

    - table: "warehouses"
      name: "warehouses_delete"
      operation: "DELETE"
      using: |
        org_id = (SELECT org_id FROM users WHERE id = auth.uid())
        AND (
          (SELECT r.code FROM roles r JOIN users u ON u.role_id = r.id WHERE u.id = auth.uid())
          IN ('SUPER_ADMIN', 'ADMIN')
        )
      description: "Only super admins and admins can delete warehouses (soft delete preferred)"

# Triggers
triggers:
  - name: "ensure_single_default_warehouse"
    description: "Ensures only one warehouse is default per org (atomic operation)"
    table: "warehouses"
    timing: "BEFORE INSERT OR UPDATE OF is_default"
    for_each: "ROW"
    when: "NEW.is_default = true"
    function: |
      CREATE OR REPLACE FUNCTION ensure_single_default_warehouse()
      RETURNS TRIGGER AS $$
      BEGIN
        IF NEW.is_default = true THEN
          UPDATE warehouses
          SET is_default = false, updated_at = NOW()
          WHERE org_id = NEW.org_id
            AND id != NEW.id
            AND is_default = true;
        END IF;
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;

    rationale: "Prevents race conditions when setting default warehouse"

  - name: "update_warehouses_updated_at"
    description: "Auto-update updated_at timestamp"
    table: "warehouses"
    timing: "BEFORE UPDATE"
    for_each: "ROW"
    function: |
      CREATE OR REPLACE FUNCTION update_updated_at_column()
      RETURNS TRIGGER AS $$
      BEGIN
        NEW.updated_at = NOW();
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;

# Field Notes
field_notes:
  type:
    description: "Warehouse classification for inventory categorization"
    values:
      - code: "GENERAL"
        label: "General"
        description: "Multi-purpose warehouse"
        badge_color: "blue"
      - code: "RAW_MATERIALS"
        label: "Raw Materials"
        description: "Incoming ingredients and materials"
        badge_color: "green"
      - code: "WIP"
        label: "WIP"
        description: "Work in progress inventory"
        badge_color: "yellow"
      - code: "FINISHED_GOODS"
        label: "Finished Goods"
        description: "Completed products ready for shipping"
        badge_color: "purple"
      - code: "QUARANTINE"
        label: "Quarantine"
        description: "Items on hold for quality inspection"
        badge_color: "red"

  code:
    description: "Unique warehouse identifier (2-20 chars, uppercase alphanumeric + hyphens)"
    format: "^[A-Z0-9-]{2,20}$"
    examples: ["WH-001", "MAIN", "RAW-MAT-A", "FG-COLD"]
    validation: "Must be unique per org, uppercase enforced"

  address:
    description: "Physical address (3 lines, max 500 chars total)"
    max_length: 500
    format: "Multi-line text area"

  contact_email:
    description: "Warehouse manager/contact email"
    validation: "Standard email format"
    max_length: 255

  contact_phone:
    description: "Warehouse contact phone"
    max_length: 20
    format: "Flexible (supports international formats)"

  is_default:
    description: "Default warehouse for new inventory operations"
    constraint: "Only one per org (enforced by trigger)"
    behavior: "Setting to true automatically unsets previous default"

  location_count:
    description: "Denormalized count of locations in warehouse"
    maintenance: "Updated by triggers in Story 01.9 (Locations CRUD)"
    initial_value: 0

# Related Tables (Future Stories)
related_tables:
  - name: "locations"
    story: "01.9"
    relationship: "One warehouse has many locations"
    fk: "locations.warehouse_id → warehouses.id"

  - name: "license_plates"
    story: "05.x"
    relationship: "License plates track inventory at warehouse/location"
    fk: "license_plates.warehouse_id → warehouses.id"

  - name: "user_warehouses"
    story: "01.5b"
    relationship: "User warehouse access control"
    fk: "user_warehouses.warehouse_id → warehouses.id"

# Seed Data (Optional)
seed_data:
  description: "Optional demo warehouse for new orgs (created by onboarding wizard)"
  example:
    - code: "MAIN"
      name: "Main Warehouse"
      type: "GENERAL"
      is_default: true
      is_active: true
  note: "Seed data created by onboarding wizard (Story 01.14), not in migration"
