# Story 06.24 - CCP Monitoring Scanner - Database Context
# Generated: 2025-01-15

# Note: This story REUSES the haccp_ccp_monitoring table from story 06.23
# No new database tables or migrations required.

tables:
  haccp_ccp_monitoring:
    description: "Shared table with story 06.23 - mobile uses same schema"
    source_story: "06.23"
    mobile_usage: "Mobile scanner writes to same table as desktop"
    columns_used:
      # All columns from story 06.23 are used
      - name: "id"
        mobile_context: "Generated on offline sync"
      - name: "org_id"
        mobile_context: "From auth context"
      - name: "ccp_id"
        mobile_context: "From barcode/QR scan or dropdown"
      - name: "ccp_number"
        mobile_context: "Denormalized for offline display"
      - name: "ccp_name"
        mobile_context: "Denormalized for offline display"
      - name: "wo_id"
        mobile_context: "From WO barcode scan"
      - name: "wo_number"
        mobile_context: "Denormalized for offline display"
      - name: "monitored_value"
        mobile_context: "Entered via mobile numeric keypad"
      - name: "unit_of_measure"
        mobile_context: "Displayed from CCP definition"
      - name: "critical_limit_min"
        mobile_context: "Snapshot from CCP for offline validation"
      - name: "critical_limit_max"
        mobile_context: "Snapshot from CCP for offline validation"
      - name: "result"
        mobile_context: "Calculated offline: pass/fail/marginal"
      - name: "deviation_detected"
        mobile_context: "Calculated offline, triggers audio alert"
      - name: "corrective_action_taken"
        mobile_context: "Selected from templates or custom text"
      - name: "monitored_by"
        mobile_context: "From auth.uid() at sync time"
      - name: "monitored_at"
        mobile_context: "Timestamp from device, synced to server"
      - name: "created_at"
        mobile_context: "Set at sync time"

# Offline Storage (IndexedDB)
offline_storage:
  database_name: "MonoPilotOffline"
  version: 1
  object_stores:
    - name: "ccp_monitoring_queue"
      key_path: "id"
      description: "Offline monitoring records waiting for sync"
      max_records: 50
      indexes:
        - name: "ccp_id"
          key_path: "ccp_id"
        - name: "monitored_at"
          key_path: "monitored_at"
        - name: "synced"
          key_path: "synced"
      schema:
        - name: "id"
          type: "string (UUID v4)"
        - name: "org_id"
          type: "string"
        - name: "ccp_id"
          type: "string"
        - name: "ccp_number"
          type: "string"
        - name: "ccp_name"
          type: "string"
        - name: "wo_id"
          type: "string | null"
        - name: "wo_number"
          type: "string | null"
        - name: "monitored_value"
          type: "number"
        - name: "unit_of_measure"
          type: "string"
        - name: "critical_limit_min"
          type: "number | null"
        - name: "critical_limit_max"
          type: "number | null"
        - name: "result"
          type: "'pass' | 'fail' | 'marginal'"
        - name: "deviation_detected"
          type: "boolean"
        - name: "corrective_action_taken"
          type: "string | null"
        - name: "monitoring_method"
          type: "string"
        - name: "equipment_used"
          type: "string | null"
        - name: "monitored_by"
          type: "string (user UUID)"
        - name: "monitored_at"
          type: "string (ISO 8601 timestamp)"
        - name: "synced"
          type: "boolean (false until synced)"
        - name: "sync_error"
          type: "string | null"
        - name: "created_offline_at"
          type: "string (ISO 8601 timestamp)"

    - name: "ccp_cache"
      key_path: "id"
      description: "Cached CCP definitions for offline validation"
      indexes:
        - name: "ccp_number"
          key_path: "ccp_number"
        - name: "cached_at"
          key_path: "cached_at"
      schema:
        - name: "id"
          type: "string (CCP UUID)"
        - name: "ccp_number"
          type: "string"
        - name: "ccp_name"
          type: "string"
        - name: "critical_limit_min"
          type: "number | null"
        - name: "critical_limit_max"
          type: "number | null"
        - name: "unit_of_measure"
          type: "string"
        - name: "target_value"
          type: "number | null"
        - name: "monitoring_method"
          type: "string"
        - name: "corrective_action_std"
          type: "string"
        - name: "cached_at"
          type: "string (ISO 8601 timestamp)"

# Sync Logic
sync_strategy:
  - trigger: "WiFi reconnect"
    action: "Auto-sync all records with synced=false"
    order: "FIFO (oldest first by monitored_at)"
  - trigger: "Manual sync button"
    action: "Force sync all pending records"
  - trigger: "Background sync"
    action: "Every 5min if online, sync pending records"
  - conflict_resolution: "Server timestamp wins (no client merge)"
  - error_handling: "Store sync_error, retry max 3 times, then mark failed"

# Performance Notes
performance:
  - "IndexedDB max size: ~50MB (enough for 1000+ records)"
  - "50-record hard limit to prevent storage overflow"
  - "CCP cache refreshed every 24h or on app start"
  - "Sync batch size: 10 records at a time to avoid timeout"
  - "Network detection: navigator.onLine + ping /api/health"

# No new migrations required
migrations: []
