/**
 * Allergens - E2E Tests
 * Story: 01.12 - Allergens Management
 *
 * NOTE: Allergens are READ-ONLY (EU-mandated, system-managed)
 * No Create/Edit/Delete operations available
 *
 * Tests:
 * - List view displays all 14 EU allergens
 * - Search filters by code, English name, Polish name, German name, French name
 * - Column headers display correctly
 * - Read-only banner visible
 * - No action buttons (create/edit/delete)
 * - Product count links work
 *
 * @generated by test-generator
 */

import { test, expect } from '@playwright/test';

const ROUTE = '/settings/allergens';

test.describe('Allergens (Read-Only List)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(ROUTE);
    await page.waitForLoadState('networkidle');
  });

  test.describe('Page Layout', () => {
    test('displays page header and description', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the page
      // THEN header displays
      await expect(page.getByRole('heading', { name: /allergens/i })).toBeVisible();

      // AND description visible
      await expect(page.getByText(/EU-mandated allergens list for food labeling compliance/i)).toBeVisible();
    });

    test('displays read-only info banner', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the page
      // THEN read-only banner visible
      await expect(page.getByText(/EU-mandated allergens are system-managed and cannot be edited or deleted/i)).toBeVisible();

      // AND support contact message visible
      await expect(page.getByText(/Contact support for custom allergen requests/i)).toBeVisible();
    });

    test('displays search input with correct placeholder', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the page
      // THEN search input visible
      const searchInput = page.getByPlaceholder(/search allergens by code or name/i);
      await expect(searchInput).toBeVisible();
    });

    test('displays table with required columns', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the page
      // THEN table displays correct column headers
      const headers = page.locator('thead th');
      const headerCount = await headers.count();

      // Should have at least 7 columns: Code, Icon, Name (EN), Name EN, Name PL, Products, Status
      expect(headerCount).toBeGreaterThanOrEqual(6);

      // Check for specific header text
      await expect(page.locator('thead >> text=Code')).toBeVisible();
      await expect(page.locator('thead >> text=Icon')).toBeVisible();
      await expect(page.locator('thead >> text=Status')).toBeVisible();
      await expect(page.locator('thead >> text=Products')).toBeVisible();
    });
  });

  test.describe('Allergen List Display', () => {
    test('displays all 14 EU allergens', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the page
      // THEN all allergen rows displayed
      const rows = page.locator('tbody tr');
      const count = await rows.count();
      expect(count).toBe(14);
    });

    test('displays allergen code for each row', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the page
      // THEN allergen codes A01-A14 displayed
      const expectedCodes = ['A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08', 'A09', 'A10', 'A11', 'A12', 'A13', 'A14'];

      for (const code of expectedCodes) {
        await expect(page.getByText(code, { exact: true })).toBeVisible();
      }
    });

    test('displays allergen names in English', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the page
      // THEN allergen English names displayed (in any visible column)
      const expectedNames = ['Gluten', 'Crustaceans', 'Eggs', 'Fish', 'Peanuts', 'Soybeans', 'Milk', 'Nuts', 'Celery', 'Mustard', 'Sesame', 'Sulphites', 'Lupin', 'Molluscs'];

      for (const name of expectedNames) {
        // Look in table body for the name (appears in multiple columns, use first match)
        const nameElement = page.locator(`tbody >> text=${name}`).first();
        await expect(nameElement).toBeVisible();
      }
    });

    test('displays allergen status badges', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the page
      // THEN status badges displayed as "Active"
      const badges = page.locator('text=Active').all();
      const activeCount = (await page.locator('text=Active').all()).length;

      // All 14 allergens should be active
      expect(activeCount).toBeGreaterThanOrEqual(14);
    });

    test('displays product count column with links', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the page
      // THEN product count column visible
      await expect(page.locator('thead >> text=Products')).toBeVisible();

      // AND product count cells exist with content
      const rows = page.locator('tbody tr');
      const rowCount = await rows.count();
      expect(rowCount).toBeGreaterThan(0);
    });
  });

  test.describe('Search Functionality', () => {
    test('can search by allergen code "A07"', async ({ page }) => {
      // GIVEN allergens page loaded
      const searchInput = page.getByPlaceholder(/search allergens by code or name/i);

      // WHEN searching for code "A07"
      await searchInput.fill('A07');
      await page.waitForTimeout(150); // Wait for debounce

      // THEN only Milk (A07) displayed
      const rows = page.locator('tbody tr');
      const count = await rows.count();
      expect(count).toBe(1);
      await expect(page.locator('tbody >> text=A07').first()).toBeVisible();
    });

    test('can search by English name "Gluten"', async ({ page }) => {
      // GIVEN allergens page loaded
      const searchInput = page.getByPlaceholder(/search allergens by code or name/i);

      // WHEN searching for name "Gluten"
      await searchInput.fill('Gluten');
      await page.waitForTimeout(150); // Wait for debounce

      // THEN Gluten (A01) displayed
      const rows = page.locator('tbody tr');
      const count = await rows.count();
      expect(count).toBe(1);
      await expect(page.locator('tbody >> text=A01').first()).toBeVisible();
    });

    test('can search by Polish name "Mleko" (Milk)', async ({ page }) => {
      // GIVEN allergens page loaded
      const searchInput = page.getByPlaceholder(/search allergens by code or name/i);

      // WHEN searching for Polish name "Mleko"
      await searchInput.fill('Mleko');
      await page.waitForTimeout(150); // Wait for debounce

      // THEN Milk (A07) displayed
      const rows = page.locator('tbody tr');
      const count = await rows.count();
      expect(count).toBe(1);
    });

    test('can search by German name "Fisch" (Fish)', async ({ page }) => {
      // GIVEN allergens page loaded
      const searchInput = page.getByPlaceholder(/search allergens by code or name/i);

      // WHEN searching for German name "Fisch"
      await searchInput.fill('Fisch');
      await page.waitForTimeout(150); // Wait for debounce

      // THEN Fish (A04) displayed
      const rows = page.locator('tbody tr');
      const count = await rows.count();
      expect(count).toBe(1);
    });

    test('can search by French name "Poisson" (Fish)', async ({ page }) => {
      // GIVEN allergens page loaded
      const searchInput = page.getByPlaceholder(/search allergens by code or name/i);

      // WHEN searching for French name "Poisson"
      await searchInput.fill('Poisson');
      await page.waitForTimeout(150); // Wait for debounce

      // THEN Fish (A04) displayed
      const rows = page.locator('tbody tr');
      const count = await rows.count();
      expect(count).toBe(1);
    });

    test('search is case-insensitive', async ({ page }) => {
      // GIVEN allergens page loaded
      const searchInput = page.getByPlaceholder(/search allergens by code or name/i);

      // WHEN searching with uppercase "MILK"
      await searchInput.fill('MILK');
      await page.waitForTimeout(150); // Wait for debounce

      // THEN Milk (A07) still found
      const rows = page.locator('tbody tr');
      const count = await rows.count();
      expect(count).toBe(1);
    });

    test('search returns empty state for no matches', async ({ page }) => {
      // GIVEN allergens page loaded
      const searchInput = page.getByPlaceholder(/search allergens by code or name/i);

      // WHEN searching for non-existent term "ZZZZ"
      await searchInput.fill('ZZZZ');
      await page.waitForTimeout(150); // Wait for debounce

      // THEN empty state message displayed
      await expect(page.getByText(/no allergens match your search/i)).toBeVisible();

      // AND no allergen rows displayed
      const rows = page.locator('tbody tr');
      const count = await rows.count();
      expect(count).toBe(1); // One row with empty state message
    });

    test('can clear search to show all allergens again', async ({ page }) => {
      // GIVEN allergens page loaded with filtered results
      const searchInput = page.getByPlaceholder(/search allergens by code or name/i);
      await searchInput.fill('Milk');
      await page.waitForTimeout(150);

      // WHEN clearing search
      await searchInput.clear();
      await page.waitForTimeout(150);

      // THEN all 14 allergens displayed
      const rows = page.locator('tbody tr');
      const count = await rows.count();
      expect(count).toBe(14);
    });

    test('search filters display count updates', async ({ page }) => {
      // GIVEN allergens page loaded
      const searchInput = page.getByPlaceholder(/search allergens by code or name/i);

      // WHEN searching for allergen code "A08"
      await searchInput.fill('A08');
      await page.waitForTimeout(150); // Wait for debounce

      // THEN only matching result displayed (Nuts - A08)
      const rows = page.locator('tbody tr');
      const count = await rows.count();
      expect(count).toBe(1);
    });
  });

  test.describe('Read-Only Enforcement', () => {
    test('does NOT display Add button', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the page
      // THEN no "Add" or "Create" button visible
      const addButton = page.getByRole('button', { name: /add|create|new/i });
      await expect(addButton).not.toBeVisible();
    });

    test('does NOT display Edit buttons', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the page
      // THEN no "Edit" buttons visible
      const editButtons = page.getByRole('button', { name: /edit/i });
      const count = await editButtons.count();
      expect(count).toBe(0);
    });

    test('does NOT display Delete buttons', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the page
      // THEN no "Delete" buttons visible
      const deleteButtons = page.getByRole('button', { name: /delete|remove/i });
      const count = await deleteButtons.count();
      expect(count).toBe(0);
    });

    test('does NOT display Actions column', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the page
      // THEN no "Actions" column header
      const actionsHeader = page.getByRole('columnheader', { name: /actions/i });
      await expect(actionsHeader).not.toBeVisible();
    });

    test('rows are not clickable for editing', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN clicking on first allergen row
      const firstRow = page.locator('tbody tr').first();
      await firstRow.click();

      // THEN no edit modal/page opens
      // (page should remain on same route)
      await expect(page).toHaveURL(/\/settings\/allergens$/);
    });
  });

  test.describe('Product Count Links', () => {
    test('product count zero displays without link', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing allergens with 0 products
      // THEN product count displayed as plain text (not link)
      const zeroCountCells = page.locator('td:text("0")');
      const count = await zeroCountCells.count();

      // Assert no links in product count column for zero values
      if (count > 0) {
        const firstZeroCell = zeroCountCells.first();
        const link = firstZeroCell.locator('a');
        await expect(link).not.toBeVisible();
      }
    });

    test('product count greater than zero displays as link', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN finding allergen with products > 0
      const productCountCells = page.locator('td').filter({
        has: page.locator('a[href*="allergen_id="]')
      });

      // THEN link is visible
      const count = await productCountCells.count();

      // Only assert if there are products with allergens
      if (count > 0) {
        const firstLink = productCountCells.first().locator('a');
        await expect(firstLink).toBeVisible();
      }
    });

    test('product count link navigates to filtered products page', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN finding first product count link
      const productCountLink = page.locator('a[href*="allergen_id="]').first();

      // WHEN clicking product count link
      const linkExists = await productCountLink.count();

      if (linkExists > 0) {
        const href = await productCountLink.getAttribute('href');

        // THEN link points to products page with allergen filter
        expect(href).toContain('/technical/products');
        expect(href).toContain('allergen_id=');
      }
    });
  });

  test.describe('Allergen Icons', () => {
    test('displays icon for each allergen', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the table
      // THEN icon images displayed
      const rows = page.locator('tbody tr');
      const rowCount = await rows.count();

      // Verify at least some icons are loaded
      const images = page.locator('tbody img');
      const imageCount = await images.count();
      expect(imageCount).toBeGreaterThan(0);
    });

    test('icons have accessible alt text', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the table
      // THEN icon images have alt text
      const images = page.locator('tbody img');
      const count = await images.count();

      // Check first few images have alt text
      for (let i = 0; i < Math.min(3, count); i++) {
        const altText = await images.nth(i).getAttribute('alt');
        expect(altText).toBeTruthy();
      }
    });
  });

  test.describe('Multi-Language Tooltips', () => {
    test('displays tooltip with all translations on hover', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN hovering over first allergen row
      const firstRow = page.locator('tbody tr').first();

      // THEN wait for tooltip to appear
      await firstRow.hover();

      // Tooltips may appear after short delay
      const tooltip = page.locator('[role="tooltip"]');

      // Check if tooltip appears (may need to wait)
      const isVisible = await tooltip.isVisible().catch(() => false);

      // If tooltip visible, verify content
      if (isVisible) {
        // Tooltip should show multi-language translations
        const tooltipText = await tooltip.textContent();
        expect(tooltipText).toBeTruthy();
      }
    });
  });

  test.describe('Footer Info', () => {
    test('displays allergen count info', async ({ page }) => {
      // GIVEN allergens page loaded
      // WHEN viewing the page
      // THEN footer shows allergen count
      const footerText = page.getByText(/showing .* of \d+ allergens/i);
      await expect(footerText).toBeVisible();
    });

    test('allergen count updates when filtering', async ({ page }) => {
      // GIVEN allergens page loaded
      const searchInput = page.getByPlaceholder(/search allergens by code or name/i);

      // WHEN searching for single allergen
      await searchInput.fill('Milk');

      // THEN footer count shows 1 of 14
      const footerText = page.getByText(/showing 1 of 14 allergens/i);
      await expect(footerText).toBeVisible();
    });
  });
});
