/**
 * Tax Codes - CRUD Tests
 * Story: 01.13 - Tax Codes CRUD
 *
 * Tests:
 * - List view displays tax codes table
 * - Can create new tax code
 * - Can edit existing tax code
 * - Can delete tax code
 * - Can set tax code as default
 * - Search and filter functionality
 * - Pagination works correctly
 *
 * @generated by test-generator
 */

import { test, expect } from '@playwright/test';
import { ROUTES } from '../../fixtures/test-data';

const ROUTE = ROUTES.settingsTaxCodes;

test.describe('Tax Codes CRUD', () => {
  // Use admin auth from .auth/admin.json
  test.use({ storageState: '.auth/admin.json' });

  test.beforeEach(async ({ page }) => {
    await page.goto(ROUTE);
    await page.waitForLoadState('networkidle');
  });

  test.describe('List View', () => {
    test('displays data table with headers', async ({ page }) => {
      // Check table is visible
      const table = page.locator('table');
      await expect(table).toBeVisible();

      // Verify column headers
      await expect(page.getByRole('columnheader', { name: /code/i })).toBeVisible();
      await expect(page.getByRole('columnheader', { name: /name/i })).toBeVisible();
      await expect(page.getByRole('columnheader', { name: /rate/i })).toBeVisible();
      await expect(page.getByRole('columnheader', { name: /jurisdiction/i })).toBeVisible();
      await expect(page.getByRole('columnheader', { name: /valid from/i })).toBeVisible();
      await expect(page.getByRole('columnheader', { name: /valid to/i })).toBeVisible();
      await expect(page.getByRole('columnheader', { name: /default/i })).toBeVisible();
      await expect(page.getByRole('columnheader', { name: /status/i })).toBeVisible();
      await expect(page.getByRole('columnheader', { name: /actions/i })).toBeVisible();
    });

    test('displays page title and description', async ({ page }) => {
      await expect(page.getByRole('heading', { name: /tax codes/i })).toBeVisible();
      await expect(
        page.getByText(/manage tax codes with validity periods and default settings/i)
      ).toBeVisible();
    });

    test('displays Add Tax Code button', async ({ page }) => {
      const addButton = page.getByRole('button', { name: /add tax code/i });
      await expect(addButton).toBeVisible();
      await expect(addButton).toBeEnabled();
    });

    test('can search items by code', async ({ page }) => {
      const searchInput = page.locator('input[aria-label="Search tax codes"]');
      await expect(searchInput).toBeVisible();

      // Type search term
      await searchInput.fill('VAT');
      await page.waitForTimeout(300); // Wait for debounce (200ms) + buffer

      // Verify search results are filtered
      const rows = page.locator('tbody tr');
      const count = await rows.count();
      // If there are results, they should contain VAT
      if (count > 0) {
        const firstCell = rows.first().locator('td').first();
        const text = await firstCell.textContent();
        expect(text?.toUpperCase()).toContain('VAT');
      }
    });

    test('displays country filter dropdown', async ({ page }) => {
      // Find the country filter select
      const countryFilter = page.locator('[data-testid="country-filter"]');
      await expect(countryFilter).toBeVisible();

      // Click to open
      await countryFilter.click();
      const selectContent = page.locator('[role="listbox"]');
      await expect(selectContent).toBeVisible();
    });

    test('displays status filter dropdown', async ({ page }) => {
      // Find the status filter select
      const statusFilter = page.locator('[data-testid="status-filter"]');
      await expect(statusFilter).toBeVisible();

      // Click to open
      await statusFilter.click();
      const selectContent = page.locator('[role="listbox"]');
      await expect(selectContent).toBeVisible();
    });

    test('displays pagination controls', async ({ page }) => {
      // Check for pagination info - look for the text that contains "Showing"
      const paginationInfo = page.locator('text=/showing/i');
      await expect(paginationInfo).toBeVisible();

      // Check for pagination buttons
      const prevButton = page.getByLabel(/previous page/i);
      const nextButton = page.getByLabel(/next page/i);
      await expect(prevButton).toBeVisible();
      await expect(nextButton).toBeVisible();
    });
  });

  test.describe('Create', () => {
    test('opens create modal when clicking Add Tax Code button', async ({ page }) => {
      const addButton = page.getByRole('button', { name: /add tax code/i });
      await addButton.click();

      // Modal should be visible
      const modal = page.locator('[role="dialog"]');
      await expect(modal).toBeVisible();

      // Modal title should be "Create Tax Code"
      await expect(page.getByRole('heading', { name: /create tax code/i })).toBeVisible();

      // Form description
      await expect(
        page.getByText(/add a new tax code with validity period/i)
      ).toBeVisible();
    });

    test('displays all form fields in create modal', async ({ page }) => {
      const addButton = page.getByRole('button', { name: /add tax code/i });
      await addButton.click();

      // Check form fields exist
      await expect(page.getByLabel(/code/i)).toBeVisible();
      await expect(page.getByLabel(/jurisdiction/i)).toBeVisible();
      await expect(page.getByLabel(/^name/i)).toBeVisible();
      await expect(page.getByLabel(/rate \(%\)/i)).toBeVisible();
      await expect(page.getByLabel(/valid from/i)).toBeVisible();
      await expect(page.getByLabel(/valid to/i)).toBeVisible();
      await expect(page.getByRole('checkbox', { name: /set as default/i })).toBeVisible();
    });

    test('validates required fields on submit', async ({ page }) => {
      const addButton = page.getByRole('button', { name: /add tax code/i });
      await addButton.click();

      // Click submit without filling fields
      const submitButton = page.getByRole('button', { name: /create/i });
      await submitButton.click();
      await page.waitForTimeout(500);

      // Validation errors should appear
      const errors = page.locator('text=/required|must be/i');
      const errorCount = await errors.count();
      expect(errorCount).toBeGreaterThan(0);
    });

    test('validates code format', async ({ page }) => {
      const addButton = page.getByRole('button', { name: /add tax code/i });
      await addButton.click();

      const codeInput = page.getByLabel(/code/i).first();

      // Try invalid code (too short)
      await codeInput.fill('V');

      const submitButton = page.getByRole('button', { name: /create/i });
      await submitButton.click();
      await page.waitForTimeout(500);

      // Error about code format
      const errors = page.locator('text=/must be.*alphanumeric/i');
      expect(await errors.count()).toBeGreaterThan(0);
    });

    test('validates rate between 0 and 100', async ({ page }) => {
      const addButton = page.getByRole('button', { name: /add tax code/i });
      await addButton.click();

      const rateInput = page.getByLabel(/rate \(%\)/i);

      // Try invalid rate (> 100)
      await rateInput.fill('150');

      const submitButton = page.getByRole('button', { name: /create/i });
      await submitButton.click();
      await page.waitForTimeout(500);

      // Error about rate range
      const errors = page.locator('text=/between 0 and 100/i');
      expect(await errors.count()).toBeGreaterThan(0);
    });

    test('creates new tax code successfully', async ({ page }) => {
      const addButton = page.getByRole('button', { name: /add tax code/i });
      await addButton.click();

      // Fill form fields
      const codeInput = page.getByLabel(/code/i).first();
      const nameInput = page.getByLabel(/^name/i);
      const rateInput = page.getByLabel(/rate \(%\)/i);
      const validFromInput = page.getByLabel(/valid from/i);
      const jurisdictionSelect = page.getByLabel(/jurisdiction/i);

      await codeInput.fill('VAT23TEST');
      await nameInput.fill('VAT 23% Test');
      await rateInput.fill('23.00');
      await validFromInput.fill('2025-01-01');

      // Select jurisdiction
      await jurisdictionSelect.click();
      const selectContent = page.locator('[role="listbox"]');
      await expect(selectContent).toBeVisible();
      const plOption = selectContent.locator('text=PL -').first();
      await plOption.click();

      // Submit form
      const submitButton = page.getByRole('button', { name: /create/i });
      await submitButton.click();
      await page.waitForTimeout(1000);

      // Check for success message
      const successToast = page.getByText(/created successfully/i);
      await expect(successToast).toBeVisible();

      // Modal should close
      const modal = page.locator('[role="dialog"]');
      await expect(modal).not.toBeVisible();
    });

    test('can close create modal with Cancel button', async ({ page }) => {
      const addButton = page.getByRole('button', { name: /add tax code/i });
      await addButton.click();

      const cancelButton = page.getByRole('button', { name: /cancel/i });
      await cancelButton.click();

      const modal = page.locator('[role="dialog"]');
      await expect(modal).not.toBeVisible();
    });
  });

  test.describe('Edit', () => {
    test('opens edit modal when clicking row actions menu', async ({ page }) => {
      // Find first row's actions menu button
      const firstRowActions = page.locator('tbody tr').first().locator('button[aria-label="Actions"]');
      await expect(firstRowActions).toBeVisible();

      await firstRowActions.click();

      // Click Edit option
      const editOption = page.getByRole('menuitem', { name: /edit/i }).first();
      await expect(editOption).toBeVisible();
      await editOption.click();

      // Modal should open
      const modal = page.locator('[role="dialog"]');
      await expect(modal).toBeVisible();

      // Should show "Edit Tax Code" title
      await expect(page.getByRole('heading', { name: /edit tax code/i })).toBeVisible();
    });

    test('displays edit modal description', async ({ page }) => {
      const firstRowActions = page.locator('tbody tr').first().locator('button[aria-label="Actions"]');
      await firstRowActions.click();

      const editOption = page.getByRole('menuitem', { name: /edit/i }).first();
      await editOption.click();

      // Check description
      await expect(
        page.getByText(/update tax code details.*code and country cannot be changed/i)
      ).toBeVisible();
    });

    test('shows code and jurisdiction as read-only in edit mode', async ({ page }) => {
      const firstRowActions = page.locator('tbody tr').first().locator('button[aria-label="Actions"]');
      await firstRowActions.click();

      const editOption = page.getByRole('menuitem', { name: /edit/i }).first();
      await editOption.click();

      // Code and country should be disabled
      const codeInput = page.getByLabel(/code/i).first();
      const jurisdictionSelect = page.getByLabel(/jurisdiction/i);

      await expect(codeInput).toBeDisabled();
      await expect(jurisdictionSelect).toBeDisabled();

      // Other fields should be editable
      const nameInput = page.getByLabel(/^name/i);
      await expect(nameInput).toBeEnabled();
    });

    test('updates tax code successfully', async ({ page }) => {
      const firstRowActions = page.locator('tbody tr').first().locator('button[aria-label="Actions"]');
      await firstRowActions.click();

      const editOption = page.getByRole('menuitem', { name: /edit/i }).first();
      await editOption.click();

      // Get original name for comparison
      const nameInput = page.getByLabel(/^name/i);
      const originalName = await nameInput.inputValue();

      // Update name
      const newName = `${originalName} - Updated`;
      await nameInput.clear();
      await nameInput.fill(newName);

      // Submit
      const submitButton = page.getByRole('button', { name: /update/i });
      await submitButton.click();
      await page.waitForTimeout(1000);

      // Check for success message
      const successToast = page.getByText(/updated successfully/i);
      await expect(successToast).toBeVisible();

      // Modal should close
      const modal = page.locator('[role="dialog"]');
      await expect(modal).not.toBeVisible();
    });

    test('can close edit modal with Cancel button', async ({ page }) => {
      const firstRowActions = page.locator('tbody tr').first().locator('button[aria-label="Actions"]');
      await firstRowActions.click();

      const editOption = page.getByRole('menuitem', { name: /edit/i }).first();
      await editOption.click();

      const cancelButton = page.getByRole('button', { name: /cancel/i });
      await cancelButton.click();

      const modal = page.locator('[role="dialog"]');
      await expect(modal).not.toBeVisible();
    });
  });

  test.describe('Set Default', () => {
    test('shows Set as Default option in actions menu', async ({ page }) => {
      const firstRowActions = page.locator('tbody tr').first().locator('button[aria-label="Actions"]');
      await firstRowActions.click();

      // "Set as Default" should be visible (unless already default)
      const setDefaultOption = page.getByRole('menuitem', { name: /set as default/i });
      const isVisible = await setDefaultOption.isVisible().catch(() => false);

      // It's ok if it's not visible (tax code is already default) or visible
      expect([true, false]).toContain(isVisible);
    });

    test('opens confirmation dialog for setting default', async ({ page }) => {
      // Find a non-default tax code or use first one
      const rows = page.locator('tbody tr');
      let targetRow = null;

      // Try to find a non-default row
      for (let i = 0; i < await rows.count(); i++) {
        const row = rows.nth(i);
        const defaultBadge = row.locator('[role="cell"]').nth(6); // Default column
        const badgeText = await defaultBadge.textContent();
        if (badgeText && !badgeText.includes('Yes')) {
          targetRow = row;
          break;
        }
      }

      if (!targetRow) {
        targetRow = rows.first();
      }

      const actionButton = targetRow.locator('button[aria-label="Actions"]');
      await actionButton.click();

      const setDefaultOption = page.getByRole('menuitem', { name: /set as default/i });
      const isVisible = await setDefaultOption.isVisible().catch(() => false);

      if (isVisible) {
        await setDefaultOption.click();

        // Confirmation dialog should appear
        const alertDialog = page.locator('[role="alertdialog"]');
        await expect(alertDialog).toBeVisible();

        // Dialog title
        await expect(page.getByRole('heading', { name: /set default tax code/i })).toBeVisible();
      }
    });

    test('confirms setting tax code as default', async ({ page }) => {
      const rows = page.locator('tbody tr');
      let targetRow = null;

      for (let i = 0; i < await rows.count(); i++) {
        const row = rows.nth(i);
        const defaultBadge = row.locator('[role="cell"]').nth(6);
        const badgeText = await defaultBadge.textContent();
        if (badgeText && !badgeText.includes('Yes')) {
          targetRow = row;
          break;
        }
      }

      if (targetRow) {
        const actionButton = targetRow.locator('button[aria-label="Actions"]');
        await actionButton.click();

        const setDefaultOption = page.getByRole('menuitem', { name: /set as default/i });
        const isVisible = await setDefaultOption.isVisible().catch(() => false);

        if (isVisible) {
          await setDefaultOption.click();

          // Click Confirm button
          const confirmButton = page.getByRole('button', { name: /confirm/i });
          await expect(confirmButton).toBeVisible();
          await confirmButton.click();
          await page.waitForTimeout(1000);

          // Success message should appear
          const successToast = page.getByText(/set as default/i);
          await expect(successToast).toBeVisible();
        }
      }
    });
  });

  test.describe('Delete', () => {
    test('shows Delete option in actions menu', async ({ page }) => {
      const firstRowActions = page.locator('tbody tr').first().locator('button[aria-label="Actions"]');
      await firstRowActions.click();

      const deleteOption = page.getByRole('menuitem', { name: /delete/i });
      await expect(deleteOption).toBeVisible();
    });

    test('shows confirmation dialog when clicking Delete', async ({ page }) => {
      const firstRowActions = page.locator('tbody tr').first().locator('button[aria-label="Actions"]');
      await firstRowActions.click();

      const deleteOption = page.getByRole('menuitem', { name: /delete/i });
      await deleteOption.click();

      // Confirmation dialog should appear
      const alertDialog = page.locator('[role="alertdialog"]');
      await expect(alertDialog).toBeVisible();

      // Dialog title
      await expect(page.getByRole('heading', { name: /delete tax code/i })).toBeVisible();
    });

    test('displays warning text in delete confirmation', async ({ page }) => {
      const firstRowActions = page.locator('tbody tr').first().locator('button[aria-label="Actions"]');
      await firstRowActions.click();

      const deleteOption = page.getByRole('menuitem', { name: /delete/i });
      await deleteOption.click();

      // Should contain warning about action being undone
      const warningText = page.getByText(/this action cannot be undone/i);
      await expect(warningText).toBeVisible();
    });

    test('cancels delete when clicking Cancel button', async ({ page }) => {
      const initialCount = await page.locator('tbody tr').count();

      const firstRowActions = page.locator('tbody tr').first().locator('button[aria-label="Actions"]');
      await firstRowActions.click();

      const deleteOption = page.getByRole('menuitem', { name: /delete/i });
      await deleteOption.click();

      // Click Cancel
      const cancelButton = page.getByRole('button', { name: /cancel/i });
      await cancelButton.click();

      // Dialog should close
      const alertDialog = page.locator('[role="alertdialog"]');
      await expect(alertDialog).not.toBeVisible();

      // Row count should be unchanged
      const newCount = await page.locator('tbody tr').count();
      expect(newCount).toBe(initialCount);
    });

    test('deletes tax code after confirmation', async ({ page }) => {
      // Get the code of first tax code before deletion
      const firstRowCode = await page
        .locator('tbody tr')
        .first()
        .locator('td')
        .first()
        .textContent();

      const initialCount = await page.locator('tbody tr').count();

      const firstRowActions = page.locator('tbody tr').first().locator('button[aria-label="Actions"]');
      await firstRowActions.click();

      const deleteOption = page.getByRole('menuitem', { name: /delete/i });
      await deleteOption.click();

      // Click Delete button in confirmation dialog
      const deleteButton = page.locator('[role="alertdialog"]').locator('button:has-text("Delete")');
      await deleteButton.click();
      await page.waitForTimeout(1000);

      // Success message should appear
      const successToast = page.getByText(/deleted successfully/i);
      await expect(successToast).toBeVisible();

      // Row count should decrease
      await page.waitForTimeout(500);
      const newCount = await page.locator('tbody tr').count();
      expect(newCount).toBe(initialCount - 1);

      // First row should no longer contain the deleted code
      const firstRowCodeAfter = await page
        .locator('tbody tr')
        .first()
        .locator('td')
        .first()
        .textContent();
      expect(firstRowCodeAfter).not.toBe(firstRowCode);
    });
  });

  test.describe('Pagination', () => {
    test('next page button navigates to next page', async ({ page }) => {
      // Get initial page number
      const initialPageText = await page.locator('text=/page.*of/i').first().textContent();

      const nextButton = page.getByLabel(/next page/i);

      // Check if next button is enabled
      const isNextEnabled = await nextButton.isEnabled();

      if (isNextEnabled) {
        await nextButton.click();
        await page.waitForTimeout(500);

        // Page number should change
        const newPageText = await page.locator('text=/page.*of/i').first().textContent();
        expect(newPageText).not.toBe(initialPageText);
      }
    });

    test('previous page button navigates to previous page', async ({ page }) => {
      const nextButton = page.getByLabel(/next page/i);

      // Go to next page first
      const isNextEnabled = await nextButton.isEnabled();
      if (isNextEnabled) {
        await nextButton.click();
        await page.waitForTimeout(500);

        const pageTextOnNextPage = await page.locator('text=/page.*of/i').first().textContent();

        const prevButton = page.getByLabel(/previous page/i);
        await prevButton.click();
        await page.waitForTimeout(500);

        const pageTextOnPrevPage = await page.locator('text=/page.*of/i').first().textContent();

        // Should be back to page 1
        expect(pageTextOnPrevPage).toContain('Page 1');
      }
    });
  });
});
