# Story 03.3 - Database Schema
# Purpose: Tables, RLS policies, triggers, indexes
# Agent: BACKEND-DEV (database focus)

migrations:
  - path: "supabase/migrations/XXX_create_purchase_orders_table.sql"
    type: "migration"
    description: "PO header table with audit fields and calculated totals"
  - path: "supabase/migrations/XXX_create_purchase_order_lines_table.sql"
    type: "migration"
    description: "PO lines table with quantity, price, line_total"
  - path: "supabase/migrations/XXX_create_po_status_history_table.sql"
    type: "migration"
    description: "Status change audit trail"
  - path: "supabase/migrations/XXX_po_rls_policies.sql"
    type: "migration"
    description: "RLS policies following ADR-013 pattern"
  - path: "supabase/migrations/XXX_po_triggers.sql"
    type: "migration"
    description: "Auto-calculation triggers for line and header totals"
  - path: "supabase/migrations/XXX_po_number_function.sql"
    type: "migration"
    description: "Function to generate PO-YYYY-NNNNN numbers"

tables:
  - name: "purchase_orders"
    description: "Purchase Order header with supplier, dates, totals"
    columns:
      - { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()" }
      - { name: "org_id", type: "UUID", constraints: "NOT NULL REFERENCES organizations(id) ON DELETE CASCADE" }
      - { name: "po_number", type: "VARCHAR(20)", constraints: "NOT NULL" }
      - { name: "supplier_id", type: "UUID", constraints: "NOT NULL REFERENCES suppliers(id)" }
      - { name: "currency", type: "VARCHAR(3)", constraints: "NOT NULL DEFAULT 'PLN'" }
      - { name: "tax_code_id", type: "UUID", constraints: "REFERENCES tax_codes(id)" }
      - { name: "expected_delivery_date", type: "DATE", constraints: "NOT NULL" }
      - { name: "warehouse_id", type: "UUID", constraints: "NOT NULL REFERENCES warehouses(id)" }
      - { name: "status", type: "VARCHAR(20)", constraints: "NOT NULL DEFAULT 'draft'" }
      - { name: "payment_terms", type: "VARCHAR(50)", constraints: "" }
      - { name: "shipping_method", type: "VARCHAR(100)", constraints: "" }
      - { name: "notes", type: "TEXT", constraints: "" }
      - { name: "internal_notes", type: "TEXT", constraints: "" }
      # Approval fields (used by Story 03.5)
      - { name: "approval_status", type: "VARCHAR(20)", constraints: "" }
      - { name: "approved_by", type: "UUID", constraints: "REFERENCES users(id)" }
      - { name: "approved_at", type: "TIMESTAMPTZ", constraints: "" }
      - { name: "approval_notes", type: "TEXT", constraints: "" }
      # Calculated totals (denormalized for performance)
      - { name: "subtotal", type: "DECIMAL(15,4)", constraints: "DEFAULT 0" }
      - { name: "tax_amount", type: "DECIMAL(15,4)", constraints: "DEFAULT 0" }
      - { name: "total", type: "DECIMAL(15,4)", constraints: "DEFAULT 0" }
      - { name: "discount_total", type: "DECIMAL(15,4)", constraints: "DEFAULT 0" }
      # Audit fields
      - { name: "created_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }
      - { name: "updated_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }
      - { name: "created_by", type: "UUID", constraints: "REFERENCES users(id)" }
      - { name: "updated_by", type: "UUID", constraints: "REFERENCES users(id)" }
    constraints:
      - "UNIQUE(org_id, po_number)"
      - "CHECK (status IN ('draft', 'submitted', 'pending_approval', 'confirmed', 'receiving', 'closed', 'cancelled'))"
      - "CHECK (currency IN ('PLN', 'EUR', 'USD', 'GBP'))"
    rls: true
    rls_pattern: "org_id = (SELECT org_id FROM users WHERE id = auth.uid())"
    indexes:
      - "idx_po_org_status ON purchase_orders(org_id, status)"
      - "idx_po_supplier ON purchase_orders(supplier_id)"
      - "idx_po_delivery_date ON purchase_orders(expected_delivery_date)"
      - "idx_po_warehouse ON purchase_orders(warehouse_id)"
      - "idx_po_created_at ON purchase_orders(created_at DESC)"
      - "idx_po_org_number ON purchase_orders(org_id, po_number)"

  - name: "purchase_order_lines"
    description: "PO line items with product, quantity, pricing"
    columns:
      - { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()" }
      - { name: "po_id", type: "UUID", constraints: "NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE" }
      - { name: "line_number", type: "INTEGER", constraints: "NOT NULL" }
      - { name: "product_id", type: "UUID", constraints: "NOT NULL REFERENCES products(id)" }
      - { name: "quantity", type: "DECIMAL(15,4)", constraints: "NOT NULL" }
      - { name: "uom", type: "VARCHAR(20)", constraints: "NOT NULL" }
      - { name: "unit_price", type: "DECIMAL(15,4)", constraints: "NOT NULL" }
      - { name: "discount_percent", type: "DECIMAL(5,2)", constraints: "DEFAULT 0" }
      - { name: "discount_amount", type: "DECIMAL(15,4)", constraints: "DEFAULT 0" }
      - { name: "line_total", type: "DECIMAL(15,4)", constraints: "NOT NULL" }
      - { name: "expected_delivery_date", type: "DATE", constraints: "" }
      - { name: "confirmed_delivery_date", type: "DATE", constraints: "" }
      - { name: "received_qty", type: "DECIMAL(15,4)", constraints: "DEFAULT 0" }
      - { name: "notes", type: "TEXT", constraints: "" }
      - { name: "created_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }
      - { name: "updated_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }
    constraints:
      - "UNIQUE(po_id, line_number)"
      - "CHECK (quantity > 0)"
      - "CHECK (unit_price >= 0)"
      - "CHECK (discount_percent >= 0 AND discount_percent <= 100)"
      - "CHECK (received_qty >= 0 AND received_qty <= quantity * 1.1)"
    rls: true
    rls_pattern: "EXISTS (SELECT 1 FROM purchase_orders po WHERE po.id = purchase_order_lines.po_id AND po.org_id = (SELECT org_id FROM users WHERE id = auth.uid()))"
    indexes:
      - "idx_po_lines_po ON purchase_order_lines(po_id)"
      - "idx_po_lines_product ON purchase_order_lines(product_id)"
      - "idx_po_lines_po_line ON purchase_order_lines(po_id, line_number)"

  - name: "po_status_history"
    description: "Audit trail of PO status changes"
    columns:
      - { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()" }
      - { name: "po_id", type: "UUID", constraints: "NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE" }
      - { name: "from_status", type: "VARCHAR(20)", constraints: "" }
      - { name: "to_status", type: "VARCHAR(20)", constraints: "NOT NULL" }
      - { name: "changed_by", type: "UUID", constraints: "REFERENCES users(id)" }
      - { name: "changed_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }
      - { name: "notes", type: "TEXT", constraints: "" }
    rls: true
    rls_pattern: "EXISTS (SELECT 1 FROM purchase_orders po WHERE po.id = po_status_history.po_id AND po.org_id = (SELECT org_id FROM users WHERE id = auth.uid()))"
    indexes:
      - "idx_po_history_po ON po_status_history(po_id)"
      - "idx_po_history_changed_at ON po_status_history(changed_at DESC)"

# RLS Policies (ADR-013)
rls_policies:
  pattern: "Users Table Lookup"
  pattern_sql: "(SELECT org_id FROM users WHERE id = auth.uid())"

  policies:
    # purchase_orders policies
    - table: "purchase_orders"
      name: "po_select"
      operation: "SELECT"
      using: "org_id = (SELECT org_id FROM users WHERE id = auth.uid())"

    - table: "purchase_orders"
      name: "po_insert"
      operation: "INSERT"
      with_check: >
        org_id = (SELECT org_id FROM users WHERE id = auth.uid())
        AND (
          (SELECT r.code FROM roles r JOIN users u ON u.role_id = r.id WHERE u.id = auth.uid())
          IN ('owner', 'admin', 'planner', 'production_manager')
        )

    - table: "purchase_orders"
      name: "po_update"
      operation: "UPDATE"
      using: >
        org_id = (SELECT org_id FROM users WHERE id = auth.uid())
        AND (
          (SELECT r.code FROM roles r JOIN users u ON u.role_id = r.id WHERE u.id = auth.uid())
          IN ('owner', 'admin', 'planner', 'production_manager')
        )

    - table: "purchase_orders"
      name: "po_delete"
      operation: "DELETE"
      using: >
        org_id = (SELECT org_id FROM users WHERE id = auth.uid())
        AND status = 'draft'
        AND (
          (SELECT r.code FROM roles r JOIN users u ON u.role_id = r.id WHERE u.id = auth.uid())
          IN ('owner', 'admin', 'planner')
        )

    # purchase_order_lines policies (via FK to purchase_orders)
    - table: "purchase_order_lines"
      name: "po_lines_select"
      operation: "SELECT"
      using: >
        EXISTS (
          SELECT 1 FROM purchase_orders po
          WHERE po.id = purchase_order_lines.po_id
            AND po.org_id = (SELECT org_id FROM users WHERE id = auth.uid())
        )

    - table: "purchase_order_lines"
      name: "po_lines_insert"
      operation: "INSERT"
      with_check: >
        EXISTS (
          SELECT 1 FROM purchase_orders po
          WHERE po.id = purchase_order_lines.po_id
            AND po.org_id = (SELECT org_id FROM users WHERE id = auth.uid())
            AND po.status IN ('draft', 'submitted')
        )

    - table: "purchase_order_lines"
      name: "po_lines_update"
      operation: "UPDATE"
      using: >
        EXISTS (
          SELECT 1 FROM purchase_orders po
          WHERE po.id = purchase_order_lines.po_id
            AND po.org_id = (SELECT org_id FROM users WHERE id = auth.uid())
            AND po.status IN ('draft', 'submitted')
        )

    - table: "purchase_order_lines"
      name: "po_lines_delete"
      operation: "DELETE"
      using: >
        EXISTS (
          SELECT 1 FROM purchase_orders po
          WHERE po.id = purchase_order_lines.po_id
            AND po.org_id = (SELECT org_id FROM users WHERE id = auth.uid())
            AND po.status = 'draft'
        )
        AND received_qty = 0

    # po_status_history policies
    - table: "po_status_history"
      name: "po_history_select"
      operation: "SELECT"
      using: >
        EXISTS (
          SELECT 1 FROM purchase_orders po
          WHERE po.id = po_status_history.po_id
            AND po.org_id = (SELECT org_id FROM users WHERE id = auth.uid())
        )

    - table: "po_status_history"
      name: "po_history_insert"
      operation: "INSERT"
      with_check: >
        EXISTS (
          SELECT 1 FROM purchase_orders po
          WHERE po.id = po_status_history.po_id
            AND po.org_id = (SELECT org_id FROM users WHERE id = auth.uid())
        )

# Triggers
triggers:
  - name: "tr_po_line_calc_totals"
    table: "purchase_order_lines"
    timing: "BEFORE INSERT OR UPDATE"
    event: "quantity, unit_price, discount_percent"
    function: "calc_po_line_totals"
    description: |
      Calculates discount_amount and line_total:
      discount_amount = ROUND(quantity * unit_price * (discount_percent / 100), 4)
      line_total = ROUND((quantity * unit_price) - discount_amount, 4)

  - name: "tr_po_update_totals"
    table: "purchase_order_lines"
    timing: "AFTER INSERT OR UPDATE OR DELETE"
    event: "row"
    function: "update_po_totals"
    description: |
      Recalculates purchase_orders.subtotal, tax_amount, discount_total, total
      from sum of all purchase_order_lines for that po_id

# Functions
functions:
  - name: "generate_po_number"
    params: "p_org_id UUID"
    returns: "TEXT"
    description: |
      Generates next PO number as PO-YYYY-NNNNN for org/year
      Example: PO-2024-00001, PO-2024-00002
    sql: |
      DECLARE
        v_year TEXT;
        v_next_seq INTEGER;
        v_prefix TEXT;
      BEGIN
        v_year := TO_CHAR(NOW(), 'YYYY');
        v_prefix := 'PO-' || v_year || '-';

        SELECT COALESCE(MAX(
          CAST(SUBSTRING(po_number FROM LENGTH(v_prefix) + 1) AS INTEGER)
        ), 0) + 1
        INTO v_next_seq
        FROM purchase_orders
        WHERE org_id = p_org_id
          AND po_number LIKE v_prefix || '%';

        RETURN v_prefix || LPAD(v_next_seq::TEXT, 5, '0');
      END;

  - name: "calc_po_line_totals"
    returns: "TRIGGER"
    description: "Trigger function to calculate line discount and total"
    sql: |
      BEGIN
        NEW.discount_amount := ROUND(NEW.quantity * NEW.unit_price * (NEW.discount_percent / 100), 4);
        NEW.line_total := ROUND((NEW.quantity * NEW.unit_price) - NEW.discount_amount, 4);
        RETURN NEW;
      END;

  - name: "update_po_totals"
    returns: "TRIGGER"
    description: "Trigger function to update PO header totals when lines change"
    sql: |
      DECLARE
        v_po_id UUID;
        v_subtotal DECIMAL(15,4);
        v_discount_total DECIMAL(15,4);
        v_tax_rate DECIMAL(5,2);
        v_tax_amount DECIMAL(15,4);
      BEGIN
        v_po_id := COALESCE(NEW.po_id, OLD.po_id);

        -- Calculate aggregates
        SELECT
          COALESCE(SUM(line_total), 0),
          COALESCE(SUM(discount_amount), 0)
        INTO v_subtotal, v_discount_total
        FROM purchase_order_lines
        WHERE po_id = v_po_id;

        -- Get tax rate
        SELECT COALESCE(tc.rate, 0)
        INTO v_tax_rate
        FROM purchase_orders po
        LEFT JOIN tax_codes tc ON po.tax_code_id = tc.id
        WHERE po.id = v_po_id;

        v_tax_amount := ROUND(v_subtotal * (v_tax_rate / 100), 4);

        -- Update PO totals
        UPDATE purchase_orders
        SET
          subtotal = v_subtotal,
          discount_total = v_discount_total,
          tax_amount = v_tax_amount,
          total = v_subtotal + v_tax_amount,
          updated_at = NOW()
        WHERE id = v_po_id;

        RETURN NULL;
      END;

# Status Transitions
status_transitions:
  allowed:
    - { from: "draft", to: ["submitted", "cancelled"] }
    - { from: "submitted", to: ["pending_approval", "confirmed", "cancelled"] }
    - { from: "pending_approval", to: ["confirmed", "cancelled"] }
    - { from: "confirmed", to: ["receiving", "cancelled"] }
    - { from: "receiving", to: ["closed", "cancelled"] }
    - { from: "closed", to: [] }
    - { from: "cancelled", to: [] }
  notes:
    - "submitted -> pending_approval: When approval required and total exceeds threshold"
    - "submitted -> confirmed: When no approval required"
    - "confirmed -> receiving: Triggered by first GRN creation (Epic 05)"
    - "receiving -> closed: When all lines fully received"
    - "cancelled: Only if no receipts recorded (received_qty = 0)"
