# Story 01.12 - Database Schema
# Purpose: Tables, RLS policies, seed data (14 EU allergens)
# Agent: BACKEND-DEV (database focus)

migrations:
  - path: "supabase/migrations/055_create_allergens_table.sql"
    type: "migration"
    description: "Create allergens table, seed 14 EU allergens, add indexes and RLS"

tables:
  - name: "allergens"
    description: "EU-mandated allergens (global reference data, NOT org-scoped)"
    org_scoped: false
    columns:
      - { name: "id", type: "UUID", constraints: "PRIMARY KEY DEFAULT gen_random_uuid()" }
      - { name: "code", type: "VARCHAR(10)", constraints: "UNIQUE NOT NULL" }
      - { name: "name_en", type: "VARCHAR(100)", constraints: "NOT NULL" }
      - { name: "name_pl", type: "VARCHAR(100)", constraints: "NOT NULL" }
      - { name: "name_de", type: "VARCHAR(100)", constraints: "" }
      - { name: "name_fr", type: "VARCHAR(100)", constraints: "" }
      - { name: "icon_url", type: "TEXT", constraints: "" }
      - { name: "icon_svg", type: "TEXT", constraints: "" }
      - { name: "is_eu_mandatory", type: "BOOLEAN", constraints: "DEFAULT true" }
      - { name: "is_custom", type: "BOOLEAN", constraints: "DEFAULT false" }
      - { name: "is_active", type: "BOOLEAN", constraints: "DEFAULT true" }
      - { name: "display_order", type: "INTEGER", constraints: "NOT NULL DEFAULT 0" }
      - { name: "created_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }
      - { name: "updated_at", type: "TIMESTAMPTZ", constraints: "DEFAULT NOW()" }
    rls: true
    rls_pattern: "Authenticated users can read (global reference data)"
    indexes:
      - name: "idx_allergens_code"
        type: "btree"
        columns: ["code"]
      - name: "idx_allergens_display_order"
        type: "btree"
        columns: ["display_order"]
      - name: "idx_allergens_search"
        type: "GIN"
        expression: |
          to_tsvector('simple',
            coalesce(code, '') || ' ' ||
            coalesce(name_en, '') || ' ' ||
            coalesce(name_pl, '') || ' ' ||
            coalesce(name_de, '') || ' ' ||
            coalesce(name_fr, ''))
    constraints:
      - "UNIQUE(code)"
      - "CHECK (code ~ '^A[0-9]{2}$')"

# RLS Policies
rls_policies:
  pattern: "Authenticated Read-Only (Global Reference Data)"

  policies:
    - table: "allergens"
      name: "allergens_select_authenticated"
      operation: "SELECT"
      role: "authenticated"
      using: "is_active = true"
      note: "All authenticated users can read (global reference data)"

    - table: "allergens"
      name: "No INSERT/UPDATE/DELETE policies"
      note: "Read-only in MVP - absence of policies blocks write operations"

# Seed Data (14 EU Allergens)
seed_data:
  description: "14 EU mandatory allergens per Regulation (EU) No 1169/2011"
  allergens:
    - code: "A01"
      name_en: "Gluten"
      name_pl: "Gluten"
      name_de: "Gluten"
      name_fr: "Gluten"
      icon_url: "/icons/allergens/gluten.svg"
      display_order: 1
      description: "Cereals containing gluten (wheat, rye, barley, oats, spelt, kamut)"

    - code: "A02"
      name_en: "Crustaceans"
      name_pl: "Skorupiaki"
      name_de: "Krebstiere"
      name_fr: "Crustaces"
      icon_url: "/icons/allergens/crustaceans.svg"
      display_order: 2

    - code: "A03"
      name_en: "Eggs"
      name_pl: "Jaja"
      name_de: "Eier"
      name_fr: "Oeufs"
      icon_url: "/icons/allergens/eggs.svg"
      display_order: 3

    - code: "A04"
      name_en: "Fish"
      name_pl: "Ryby"
      name_de: "Fisch"
      name_fr: "Poisson"
      icon_url: "/icons/allergens/fish.svg"
      display_order: 4

    - code: "A05"
      name_en: "Peanuts"
      name_pl: "Orzeszki ziemne"
      name_de: "Erdnusse"
      name_fr: "Arachides"
      icon_url: "/icons/allergens/peanuts.svg"
      display_order: 5

    - code: "A06"
      name_en: "Soybeans"
      name_pl: "Soja"
      name_de: "Soja"
      name_fr: "Soja"
      icon_url: "/icons/allergens/soybeans.svg"
      display_order: 6

    - code: "A07"
      name_en: "Milk"
      name_pl: "Mleko"
      name_de: "Milch"
      name_fr: "Lait"
      icon_url: "/icons/allergens/milk.svg"
      display_order: 7

    - code: "A08"
      name_en: "Nuts"
      name_pl: "Orzechy"
      name_de: "Schalenfruchte"
      name_fr: "Fruits a coque"
      icon_url: "/icons/allergens/nuts.svg"
      display_order: 8

    - code: "A09"
      name_en: "Celery"
      name_pl: "Seler"
      name_de: "Sellerie"
      name_fr: "Celeri"
      icon_url: "/icons/allergens/celery.svg"
      display_order: 9

    - code: "A10"
      name_en: "Mustard"
      name_pl: "Gorczyca"
      name_de: "Senf"
      name_fr: "Moutarde"
      icon_url: "/icons/allergens/mustard.svg"
      display_order: 10

    - code: "A11"
      name_en: "Sesame"
      name_pl: "Sezam"
      name_de: "Sesam"
      name_fr: "Sesame"
      icon_url: "/icons/allergens/sesame.svg"
      display_order: 11

    - code: "A12"
      name_en: "Sulphites"
      name_pl: "Siarczyny"
      name_de: "Sulfite"
      name_fr: "Sulfites"
      icon_url: "/icons/allergens/sulphites.svg"
      display_order: 12

    - code: "A13"
      name_en: "Lupin"
      name_pl: "Lubin"
      name_de: "Lupinen"
      name_fr: "Lupin"
      icon_url: "/icons/allergens/lupin.svg"
      display_order: 13

    - code: "A14"
      name_en: "Molluscs"
      name_pl: "Mieczaki"
      name_de: "Weichtiere"
      name_fr: "Mollusques"
      icon_url: "/icons/allergens/molluscs.svg"
      display_order: 14

# Implementation Notes
implementation_notes:
  database:
    - "Create migration with allergens table"
    - "Seed 14 EU allergens in same migration"
    - "Use ON CONFLICT (code) DO NOTHING for idempotent seeding"
    - "Verify RLS policy active"
    - "Create GIN index for full-text search"
