# Story 03.14 - Database Schema
# Purpose: Existing table columns used for scheduling
# Agent: BACKEND-DEV (database focus)
# NOTE: No new migrations needed - uses existing work_orders table from 03.10

existing_tables:
  - name: "work_orders"
    description: "Work order scheduling fields (created in 03.10)"
    relevant_columns:
      - name: "planned_start_date"
        type: "DATE"
        constraints: "NOT NULL"
        usage: "Primary date for scheduling, determines which day the WO is on"

      - name: "planned_end_date"
        type: "DATE"
        constraints: ""
        usage: "Optional end date if WO spans multiple days"

      - name: "scheduled_start_time"
        type: "TIME"
        constraints: ""
        usage: "Start time within the day (e.g., 08:00)"

      - name: "scheduled_end_time"
        type: "TIME"
        constraints: ""
        usage: "End time within the day (e.g., 16:00)"

      - name: "production_line_id"
        type: "UUID"
        constraints: "REFERENCES production_lines(id)"
        usage: "Assigned production line (can be updated with schedule)"

      - name: "machine_id"
        type: "UUID"
        constraints: "REFERENCES machines(id)"
        usage: "Assigned machine (optional, can be updated with schedule)"

      - name: "status"
        type: "VARCHAR(30)"
        constraints: "NOT NULL DEFAULT 'draft'"
        usage: "Scheduling only allowed for non-terminal statuses"

      - name: "updated_at"
        type: "TIMESTAMPTZ"
        constraints: "DEFAULT NOW()"
        usage: "Auto-updated on schedule change"

      - name: "updated_by"
        type: "UUID"
        constraints: "REFERENCES users(id)"
        usage: "Track who made schedule change"

# Existing indexes (from 03.10 and 03.15)
existing_indexes:
  - name: "idx_work_orders_gantt_line"
    table: "work_orders"
    columns: ["org_id", "production_line_id", "planned_start_date", "scheduled_start_time"]
    condition: "WHERE status != 'completed'"
    purpose: "Optimize Gantt chart queries by line"

  - name: "idx_work_orders_gantt_machine"
    table: "work_orders"
    columns: ["org_id", "machine_id", "planned_start_date", "scheduled_start_time"]
    condition: "WHERE status != 'completed'"
    purpose: "Optimize Gantt chart queries by machine"

# No new migrations for MVP scheduling
migrations: []

# Database queries for scheduling
queries:
  update_schedule: |
    -- Update WO schedule (service layer handles this via Supabase client)
    UPDATE work_orders
    SET
      planned_start_date = $1,
      planned_end_date = $2,
      scheduled_start_time = $3,
      scheduled_end_time = $4,
      production_line_id = $5,
      machine_id = $6,
      updated_at = NOW(),
      updated_by = $7
    WHERE id = $8
      AND org_id = $9
      AND status NOT IN ('completed', 'cancelled', 'closed')
    RETURNING *;

  get_wo_with_schedule: |
    -- Get WO with schedule details
    SELECT
      wo.*,
      p.name AS product_name,
      p.code AS product_code,
      pl.name AS line_name,
      m.name AS machine_name
    FROM work_orders wo
    LEFT JOIN products p ON wo.product_id = p.id
    LEFT JOIN production_lines pl ON wo.production_line_id = pl.id
    LEFT JOIN machines m ON wo.machine_id = m.id
    WHERE wo.id = $1
      AND wo.org_id = $2;

# Validation rules enforced at DB level
db_constraints:
  - description: "Status must be valid"
    constraint: "status IN ('draft', 'planned', 'released', 'in_progress', 'on_hold', 'completed', 'cancelled', 'closed')"

  - description: "Time validation handled at application layer"
    note: "DB does not enforce scheduled_end_time > scheduled_start_time"
